### ISSUE TITLE
how to embed a watermark into a colorful image not a grayscale

### ISSUE THREAD

**Issue by wuguowei19880907** [nju-luke/watermarking#2]
@nju-luke hello! this is my code to do it ,but i find the watermarked.jpg has visible difference with the source jpg.

---------------------------------------------------------------------------------
    image = cv2.imread("timg.jpg")  # the timg.jpg is the source
    B, G, R = cv2.split(image)
    watermarking = watermarking()
    # watermarking.watermark()
    R = watermarking.watermark(R)
    image = cv2.merge((B.astype(np.float), G.astype(np.float), R.astype(np.float)))
    cv2.imwrite("hehe.jpg", image)  # the hehe.jpg is the watermaked.jpg

----------------------------------------------------------------------------------
![timg](https://user-images.githubusercontent.com/19338820/53154023-b535b900-35f4-11e9-8be7-fa55a6fb7b8d.jpg)  the timg.jpg
![hehe](https://user-images.githubusercontent.com/19338820/53154050-c67ec580-35f4-11e9-8305-78f725291961.jpg)  the hehe.jpg

**Comment by nju-luke** [comment]
Adding a watermark based on the wavelet transform has essentially modified the frequency information within the image, so the picture before and after watermarking will be slightly different.

**Comment by wuguowei19880907** [comment]
thanks , i get it

> Adding a watermark based on the wavelet transform has essentially modified the frequency information within the image, so the picture before and after watermarking will be slightly different.
